[project]
name = "receipt-parser"
version = "0.0.1"
requires-python = "~=3.12"
dependencies = [
    "azure-core",
    "azure-cosmos>=4.3.1",
    "azure-functions",
    "cachecontrol",
    "coverage",
    "google-auth-oauthlib",
    "jinja2==3.1.6",
    "psycopg2-binary>=2.9.11",
    "pydantic[email]",
    "six>=1.17.0",
]

[tool.black]
line-length = 90
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''

[dependency-groups]
dev = [
    "black",
    "pylint>=4.0.4",
    "pytest>=9.0.2",
    "testcontainers[postgres]>=4.13.3",
]

[tool.uv]
package = false

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple"
